name: Script-tests

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-install:
    name: Test install
    runs-on: ubuntu-latest
    steps:
      - run: docker run --name Arch-btw -v ${{ github.workspace }}:/workspace archlinux:latest
      - run: docker ps 
      - run: docker exec Arch-btw -it chmod +x /workspace/install.sh
      - run: docker exec Arch-btw -it /workspace/install.sh
  Test-arch:
    runs-on: ubuntu-latest
    name: test 
    steps:
      - run: docker run --name Arch-btw -v ${{ github.workspace }}:/workspace archlinux:latest
      - run: docker exec Arch-btw -it chmod +x /workspace/arch.sh
      - run: docker exec Arch-btw -it /workspace/arch.sh