name: Script-tests

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-install:
    name: Test install
    runs-on: ubuntu-latest
    steps:
      - run: docker run --name Arch-btw -d -v ${{ github.workspace }}:/workspace guxxdx/archguxx:1.0
      - run: docker exec Arch-btw chmod +x /workspace/install.sh
      - run: docker exec Arch-btw  /workspace/install.sh -a
  Test-arch:
    runs-on: ubuntu-latest
    name: test 
    steps:
      - run: docker run --name Arch-btw -d -v ${{ github.workspace }}:/workspace archlinux:latest sleep infinity
      - run: docker exec Arch-btw  chmod +x /workspace/arch.sh
      - run: docker exec Arch-btw  /workspace/arch.sh